# Generated by Django 4.0.5 on 2022-07-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Please enter the name.', max_length=100, verbose_name='memo')),
                ('amount', models.BigIntegerField(blank=True, null=True, verbose_name='amount')),
                ('event_date', models.DateField(blank=True, help_text='Please enter the event date.', null=True, verbose_name='event date')),
                ('memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='memo')),
                ('is_bought', models.BooleanField(default=False, verbose_name='is bought')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
