# Generated by Django 4.0.5 on 2022-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='is registered'),
        ),
    ]
