# Generated by Django 4.0.5 on 2022-07-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
        ('shopping', '0003_todo_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expenditure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.expenditures'),
        ),
    ]
