name: Deploy to sumuma Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
      - name: prepare .ssh dir
        run: mkdir -p .ssh && chmod 700 .ssh
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy with lftp
        run: lftp -e "set net:max-retries 1; set sftp:connect-program \"ssh -a -x -p $SSH_PORT -i .ssh/id_rsa -o StrictHostKeyChecking=no\"; connect sftp://$SSH_USER:@$SSH_HOST; mirror -nR -x .git -x .ssh ./ $SSH_DIR; quit"
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_DIR: ${{ secrets.SSH_DIR }}
      - name: Setup Django
        run: |
          ssh $SSH_USER@$SSH_HOST -p $SSH_PORT -i .ssh/id_rsa " \
          cd $SSH_DIR; \
          source env/bin/activate; \
          source ~/.bashrc; \
          poetry install; \
          source env/bin/activate; \
          python manage.py migrate; \
          python manage.py collectstatic --noinput; \
          systemctl restart nginx; \
          systemctl restart uwsgi"
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_DIR: ${{ secrets.SSH_DIR }}
